config/routes.rb
Comeby::Application.routes.draw do
  devise_for :users
  root 'mainpages#index'
  get 'privacy', to: 'mainpages#privacy'
  get 'copyright', to: 'mainpages#copyright'
  get 'disclaimer', to: 'mainpages#disclaimer'
  get 'terms', to: 'mainpages#terms'

  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end

  resources :users, only: :show
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  
  belongs_to :user
  belongs_to :place
end

app/models/place.rb
class Place < ActiveRecord::Base

  belongs_to :user
  has_many :comments  
  has_many :photos

  geocoded_by :address
  after_validation :geocode

  validates :name, presence: true, :length => { :minimum => 3 }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments
  has_many :photos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   before_action :authenticate_user!
  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

  def comment_params
    params.require(:comment).permit(:review, :rating)
  end
end

app/controllers/mainpages_controller.rb
class MainpagesController < ApplicationController
  def index
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params)
    redirect_to place_path(@place)
  end

  private

  def photo_params
    params.require(:photo).permit(:picture, :caption)
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @places = Place.all
      
  end

  def show
    @place = Place.find(params[:id])   
    @comment = Comment.new
    @photo = Photo.new
  end

  def new
    @place = Place.new
  end

  
def destroy
    @place = Place.find(params[:id])
    
    @place.destroy
    redirect_to places_path

  end


  def create
    Place.create(place_params)
    redirect_to places_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :address, :description)
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end

	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/mainpages_helper.rb
module MainpagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Place and Plan</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrap">
  <nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Place and Plan', root_path, class: 'navbar-brand' %>
    </div>

<!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">          
    <ul class="nav navbar-nav navbar-right">   
      <li><%= link_to 'Add a Place', new_place_path %></li>  
      
      <% if user_signed_in? %>
      <li><%= link_to 'My Profile', user_path(current_user) %></li>
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
      <% else %>

      <!-- Log in modal -->
        
      <li><%= link_to 'Log in', new_user_session_path %></li>
      

      <!-- Sign up modal -->
        <li><%= link_to 'Sign up', new_user_registration_path %></li>  

      <% end %>              
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


 

<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>
</div>

<br class="clr" />




<!-- footer -->
<div id="footer">
  <div class="container">

    

      <div class="col-xs-12 col-sm-4 about">
        <b>About</b>
        <br />
        <%= link_to 'Privacy Policy', privacy_path %>
        <br />
        <%= link_to 'Copyright Policy', copyright_path %>
        <br />
        <%= link_to 'Website Disclaimer', disclaimer_path %>
        <br />
        <%= link_to 'Terms of Service', terms_path %>
        <br />
      </div>

      <div class="col-xs-12 col-sm-4 social">
        <b>Social</b>
        <br />          
        <%= link_to 'https://www.facebook.com' do %>
        <%= image_tag 'facebook.png', class: 'social-button' %>
        <% end %>
        <%= link_to 'https://www.instagram.com' do %>
        <%= image_tag 'instagram.png', class: 'social-button' %>
        <% end %>
      </div>

      <div class="col-xs-12 col-sm-4">
        <b>Contact</b>
        <br />
        placeandplan@gmail.com
        <br />
        South Korea
      </div>
    </div>
</div>

</body>
</html>

app/views/mainpages/copyright.html.erb
<h1>Copyright Policy</h1>
This website and its content is copyright of Place and Plan - © Place and Plan 2016. All rights reserved. Any redistribution or reproduction of part or all of the contents in any form is prohibited other than the following:
you may print or download to a local hard disk extracts for your personal and non-commercial use only
you may copy the content to individual third parties for their personal use, but only if you acknowledge the website as the source of the material
You may not, except with our express written permission, distribute or commercially exploit the content. Nor may you transmit it or store it in any other website or other form of electronic retrieval system.

app/views/mainpages/disclaimer.html.erb
<h1>Website disclaimer </h1>
The information contained in this website is for general information purposes only. The information is provided by Place and Plan and while we endeavour to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk. In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website. Through this website you are able to link to other websites which are not under the control of Place and Plan. We have no control over the nature, content and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them. Every effort is made to keep the website up and running smoothly. However, Place and Plan takes no responsibility for, and will not be liable for, the website being temporarily unavailable due to technical issues beyond our control.

app/views/mainpages/index.html.erb
<!-- Code for Carousel -->
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
       <%= image_tag 'slide1.JPG', class: 'img-responsive' %>      
    </div>

    <div class="item">
    <%= image_tag 'slide2.JPG', class: 'img-responsive' %>    
  </div>

  <div class="item">
    <%= image_tag 'slide3.jpg', class: 'img-responsive' %>    
  </div>
  </div>  
</div>


<br /><br />
<!-- search input -->
<div class="row">  
  <div class="col-xs-3 col-xs-offset-4">
    <div class="input-group input-group-lg">
      <input type="text" class="form-control" placeholder="Search for...">
      <span class="input-group-btn">
        <%= submit_tag "Search", class: 'btn btn-danger btn-lg' %>        
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->







<br /><br /><br />

<!-- 3 images -->
<div class="col-xs-10 col-xs-offset-1 features text-center">  
<div class="icon-container">

  <div class="main-box col-sm-4">    
    <%= link_to (image_tag ('icon.png')), places_path %>
    <div class="center"><h1><%= link_to 'Seoul', places_path %></h1></div>    
  </div>

  <div class="main-box col-sm-4">    
    <%= link_to (image_tag ('icon.png')), places_path %>
    <div class="center"><h1><%= link_to 'New York', places_path %></h1></div>    
  </div>

  <div class="main-box col-sm-4">    
    <%= link_to (image_tag ('icon.png')), places_path %>
    <div class="center"><h1><%= link_to 'San Francisco', places_path %></h1></div>    
  </div>

  
</div>
</div>


<br /><br /><br /><br />

app/views/mainpages/privacy.html.erb
<h1>Privacy Policy</h1>
At Place and Plan, the privacy of our visitors is of extreme importance to us (See this article to learn more about Privacy Policies.). This privacy policy document outlines the types of personal information is received and collected by Place and Plan and how it is used. Log Files Like many other Web sites, Place and Plan makes use of log files. The information inside the log files includes internet protocol (IP) addresses, type of browser, Internet Service Provider (ISP), date/time stamp, referring/exit pages, and number of clicks to analyze trends, administer the site, track user's movement around the site, and gather demographic information. IP addresses, and other such information are not linked to any information that is personally identifiable. Cookies and Web Beacons Place and Plan does use cookies to store information about visitors preferences, record user-specific information on which pages the user access or visit, customize Web page content based on visitors browser type or other information that the visitor sends via their browser. DoubleClick DART Cookie
Google, as a third party vendor, uses cookies to serve ads on Place and Plan.
Google's use of the DART cookie enables it to serve ads to users based on their visit to Place and Plan and other sites on the Internet.
Users may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy at the following URL - http://www.google.com/privacy_ads.html.
These third-party ad servers or ad networks use technology to the advertisements and links that appear on Place and Plan send directly to your browsers. They automatically receive your IP address when this occurs. Other technologies ( such as cookies, JavaScript, or Web Beacons ) may also be used by the third-party ad networks to measure the effectiveness of their advertisements and / or to personalize the advertising content that you see. Place and Plan has no access to or control over these cookies that are used by third-party advertisers. You should consult the respective privacy policies of these third-party ad servers for more detailed information on their practices as well as for instructions about how to opt-out of certain practices. Place and Plan's privacy policy does not apply to, and we cannot control the activities of, such other advertisers or web sites. If you wish to disable cookies, you may do so through your individual browser options. More detailed information about cookie management with specific web browsers can be found at the browser's respective websites.

 

app/views/mainpages/terms.html.erb
<h1>Terms and Conditions</h1>
Welcome to Place and Plan. If you continue to browse and use this website you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our privacy policy govern Place and Plan's relationship with you in relation to this website. The term Place and Plan or 'us' or 'we' refers to the owner of the website. The term 'you' refers to the user or viewer of our website. The use of this website is subject to the following terms of use:
The content of the pages of this website is for your general information and use only. It is subject to change without notice.
Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
Your use of any information or materials on this website is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products, services or information available through this website meet your specific requirements.
This website contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance and graphics. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions.
All trademarks reproduced in this website, which are not the property of, or licensed to the operator, are acknowledged on the website.
Unauthorized use of this website may give rise to a claim for damages and/or be a criminal offense.
From time to time this website may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s).
You may not create a link to this website from another website or document without Place and Plan's prior written consent.

 

app/views/places/index.html.erb
   
<br />
<div class="index-booyah-box col-xs-6">
  <h2 class="text-center">Attractions & Restaurants</h2>
  <hr />
  <!-- checkbox and filter-->

<form class="form-inline" role="form">
  <div class="form-group">
    <label>Looking for..</label>     
    <label class="checkbox-inline">
      <input type="checkbox" value="attractions">
      <%= image_tag 'see.png' %> Attractions       
    </label>
    <label class="checkbox-inline">
      <input type="checkbox" value="restaurants">
      <%= image_tag 'eat.png' %> Restaurants
    </label>
  </div>
</form>

<hr />

<form class="form-inline" role="form">
  <div class="form-group">
    <label>Neighborhoods</label>     
    <label class="checkbox-inline">
      <input type="checkbox" value="1">Hongdae
    </label>
    <label class="checkbox-inline">
      <input type="checkbox" value="2">Itaewon
    </label>
    <label class="checkbox-inline">
      <input type="checkbox" value="3">Myeongdong
    </label>
  </div>
</form>
  
  <hr />
  
  

  <% @places.each do |place| %>
  <div class="index-booyah-inner-box col-xs-5 sidebar_item">    
    <h4 id="demo" onmouseover="mouseOver()" onmouseout="mouseOut()"><%= link_to place.name, place_path(place), target: '_blank' %></h4><br />
    <i><%= place.description %></i><br />
    <%= place.address %> 
  </div>
  <script>
function mouseOver() {
    document.getElementById("demo").innerHTML = (marker, i);
}

function mouseOut() {
    document.getElementById("demo").style.color = "green";
}
</script>


   <% end %>

   
</div>


  


   
<!-- map -->
<div class="index-booyah-box col-xs-6">

<script>

var locations = [
      <% @places.each do |place| %>
        <% if place == @places.last %>
        ['<%= link_to place.name, place_path(place), target: '_blank' %><br/><%= place.description %>', <%= place.latitude %>, <%= place.longitude %>, 4]
        <% else %>
        ['<%= link_to place.name, place_path(place), target: '_blank' %><br/><%= place.description %>', <%= place.latitude %>, <%= place.longitude %>, 4],
        <% end %>
      <% end %>
    ];

function initMap() {   
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 13,
    center: {lat: 37.555130, lng: 126.970642},
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });

  var infowindow = new google.maps.InfoWindow({});

  var marker, i;

  for (i = 0; i < locations.length; i++) {    
    var marker = new google.maps.Marker({
      position: new google.maps.LatLng(locations[i][1], locations[i][2]),
      map: map      
    });

    google.maps.event.addListener(marker, 'mouseover', (function (marker, i) {
      return function () {
        infowindow.setContent(locations[i][0]);
        infowindow.open(map, marker);
      }
    })(marker, i));
  }
}


  
</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDaLIaMqoqfD9S0XFvZdxi7wd6oHlLQA-Y&callback=initMap">
  </script>






<div id="map"></div>

</div>

<br class="clr" />

<br />

app/views/places/new.html.erb
<h2>Enter Your Place Details</h2>

<%= simple_form_for @place do |f| %>
  <%= f.input :name %>
  <br />
  <%= f.input :address %> 
  <br />   
  <%= f.input :description %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>

app/views/places/show.html.erb
<div class="text-center">
  <h1><%= @place.name %></h1>    
  <br />
 <i><%= @place.address %></i>
  <br /><br />
 <b><%= @place.description %></b>
</div>
 
 <div class="clear"></div>
    
     <%= link_to 'Delete the Place', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
     
  <hr />
  





<!-- photo --><!-- photo -->

<h2 class="pull-left">Photos</h1>   &nbsp;&nbsp;

<!-- Button trigger modal -->
<button class="btn btn-primary" data-toggle="modal" data-target="#myPhotoModal">
  Add a photo
</button>
<div class="modal fade" id="myPhotoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add a photo</h4>
      </div>

      <%= simple_form_for @photo, url: place_photos_path(@place) do |p| %>

        <div class="modal-body">
          <%= p.input :picture %><br />
          <%= p.input :caption %><br />
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= p.submit "Add a Photo", class: 'btn btn-primary' %>
        <% end %>
        </div>
      
    </div>
  </div>
</div>
<div class="clear"></div>


 
<div class="row">
<% @place.photos.each do |photo| %> 
  <div class="col-xs-12 col-sm-3">
    <br />
    <div class="img-thumbnail">
      <%= image_tag photo.picture_url(:thumb) %><br />
      <div style="align: left; text-align:center;">
       <em><%= photo.caption %></em><br />
      </div>
    </div>
  </div>
<% end %>
</div>
 


<hr />





<!-- comment --><!-- comment --><!-- comment -->
<h2>Reviews</h2>
<div class="comments">    
  <% @place.comments.each do |comment| %>
    <div class="comment">
      <span class="comment_handle">
        <%= comment.user.email %> :
      </span>
      <%= comment.review %>
    </div>
    <% end %>
    <br />
    <h4>Add your review</h4>
    <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
    <%= f.input :review %>
    <%= f.submit 'Add a review', class: 'btn btn-primary pull-right' %>
    <% end %>
</div>
<br />


<hr />








<!-- map --><!-- map --><!-- map -->
<div class="show-booyah-box col-xs-10 col-xs-offset-1">
  <h2>Location</h2>
  <i><%= @place.address %></i><br /><br />
  <% if @place.latitude.present? && @place.longitude.present? %>
<script>

function initMap() {
  var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>}; 

  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 12,
    center: myLatLng
  });

  var marker = new google.maps.Marker({
    position: myLatLng,
    map: map,
    title: '<%= @place.name %>'
  });
}
</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDaLIaMqoqfD9S0XFvZdxi7wd6oHlLQA-Y&callback=initMap">
  </script>


        
<div id="map"></div>
<% end %>
</div>

     <div class="clear"></div>

app/views/users/show.html.erb

<div class="text-center">
   <h1><%= @user.email %></h1>
    <h4>Member Since: <%= @user.created_at.strftime("%B %d, %Y") %> </h4>
 </div>
<div class="clear"></div>




<hr />





<!-- Places Display -->
<h1 class="text-center">My Places</h1><br />
<div class="userbox col-xs-10 col-xs-offset-1 text-left">
<% @user.places.each do |place| %>     
      <h3><%= link_to place.name, place_path(place) %></h3><br />
      <i><%= place.address %></i><br />
      <p><%= place.description %></p><br />    
<% end %>
</div>
<div class="clear"></div>




<hr />



<!-- Comments Display -->
<h1 class="text-center">My Reviews</h1>
<br />

<div class="col-xs-10 col-xs-offset-1 text-left">
<blockquote>
<% @user.comments.each do |comment| %>
<%= link_to comment.place.name, place_path(comment.place) %>: <%= comment.review %><br />
<% end %>
</blockquote><br />
</div>



<div class="clear"></div>